const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Writes `src/environments/version.generated.ts`, the build identity the SPA shows in its footer.
 *
 * The file is gitignored on purpose: a tracked file would make the working tree dirty as soon as
 * its content differs from HEAD, which would then show up in `git describe --dirty` itself.
 *
 * Version priority:
 *   1. `APP_VERSION`       - explicit override (release pipeline, Docker build arg)
 *   2. `GITHUB_REF_NAME`   - GitHub Actions sets this for tag builds, no workflow wiring needed
 *   3. `git describe --tags --always --dirty` - local development
 *   4. `package.json` "version" - last resort (e.g. building from a source archive without .git)
 */

const projectRoot = path.join(__dirname, '..');
const outputFile = path.join(projectRoot, 'src', 'environments', 'version.generated.ts');

const SEMVER_PATTERN = /^v?\d+\.\d+\.\d+/;
const UNSAFE_CHARACTERS = /[^0-9A-Za-z.+-]/g;

function sanitize(value) {
    return String(value ?? '')
        .trim()
        .replace(UNSAFE_CHARACTERS, '');
}

function runGit(args) {
    try {
        return execFileSync('git', args, {
            cwd: projectRoot,
            encoding: 'utf8',
            stdio: ['ignore', 'pipe', 'ignore']
        }).trim();
    } catch {
        // No git (container build) or no repository: fall through to the next candidate.
        return '';
    }
}

function readPackageVersion() {
    try {
        return require(path.join(projectRoot, 'package.json')).version;
    } catch {
        return '';
    }
}

function resolveVersion() {
    const fromCiTag = process.env.GITHUB_REF_TYPE === 'tag' ? process.env.GITHUB_REF_NAME : '';

    const candidates = [
        process.env.APP_VERSION,
        fromCiTag,
        runGit(['describe', '--tags', '--always', '--dirty']),
        readPackageVersion()
    ];

    for (const candidate of candidates) {
        const value = sanitize(candidate);

        if (SEMVER_PATTERN.test(value)) {
            return `v${value.replace(/^v/i, '')}`;
        }
    }

    return 'v0.0.0';
}

function resolveCommit() {
    const sha =
        sanitize(process.env.GITHUB_SHA) || sanitize(runGit(['rev-parse', '--short', 'HEAD']));

    return sha.slice(0, 7);
}

const version = resolveVersion();
const commit = resolveCommit();
const buildDate = new Date().toISOString();

const contents =
    `// Generated by scripts/generate-version.cjs. Do not edit, do not commit.\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const APP_COMMIT = '${commit}';\n` +
    `export const APP_BUILD_DATE = '${buildDate}';\n`;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, contents);

console.log(`[version] ${version} (${commit}, ${buildDate})`);
