/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderSortField = {
    CreatedAt: 'CreatedAt',
    TotalAmount: 'TotalAmount',
    Status: 'Status',
    EventTitle: 'EventTitle',
    TicketQuantity: 'TicketQuantity'
} as const;
export type OrderSortField = typeof OrderSortField[keyof typeof OrderSortField];

