/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './order-status';
import { OrderItemDto } from './order-item-dto';


export interface OrderDto { 
    id: string;
    userId: string;
    eventId: string;
    eventTitle: string;
    eventStartsAt: string;
    eventEndsAt: string;
    status: OrderStatus;
    totalAmount: number;
    currency: string;
    createdAt: string;
    paidAt: string | null;
    cancelledAt: string | null;
    items: Array<OrderItemDto>;
}
export namespace OrderDto {
}


