/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './order-status';


export interface OrderSummaryDto { 
    id: string;
    eventId: string;
    status: OrderStatus;
    totalAmount: number;
    currency: string;
    itemCount: number;
    createdAt: string;
}
export namespace OrderSummaryDto {
}


