/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TicketStatus } from './ticket-status';


export interface TicketDto { 
    id: string;
    orderId: string;
    eventId: string;
    eventTitle: string;
    startsAt: string;
    location: string;
    ticketCategoryId: string;
    ticketCategoryName: string;
    code: string;
    status: TicketStatus;
    createdAt: string;
    usedAt: string | null;
}
export namespace TicketDto {
}


