/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthResultDto } from '../model/models';
import { LoginRequest } from '../model/models';
import { ProblemDetails } from '../model/models';
import { RegisterUserRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/Auth/login
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<AuthResultDto>;

    /**
     * 
     * 
     * @endpoint post /api/v1/Auth/register
     * @param registerUserRequest 
     */
    register(registerUserRequest: RegisterUserRequest, extraHttpRequestParams?: any): Observable<{}>;

}
