/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddTicketCategoryRequest } from '../model/models';
import { CreateEventRequest } from '../model/models';
import { EventDto } from '../model/models';
import { PagedResultOfEventDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { TicketCategoryDto } from '../model/models';
import { UpdateEventRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/Events/{id}/ticket-categories
     * @param id 
     * @param addTicketCategoryRequest 
     */
    addTicketCategory(id: string, addTicketCategoryRequest: AddTicketCategoryRequest, extraHttpRequestParams?: any): Observable<TicketCategoryDto>;

    /**
     * 
     * 
     * @endpoint post /api/v1/Events/{id}/cancel
     * @param id 
     */
    cancelEvent(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/v1/Events
     * @param createEventRequest 
     */
    createEvent(createEventRequest: CreateEventRequest, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Events/{id}
     * @param id 
     */
    getEventById(id: string, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Events
     * @param category 
     * @param status 
     * @param locationId 
     * @param page 
     * @param pageSize 
     */
    getEvents(category?: string, status?: string, locationId?: string, page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<PagedResultOfEventDto>;

    /**
     * 
     * 
     * @endpoint post /api/v1/Events/{id}/publish
     * @param id 
     */
    publishEvent(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/Events/{id}/ticket-categories/{ticketCategoryId}
     * @param id 
     * @param ticketCategoryId 
     */
    removeTicketCategory(id: string, ticketCategoryId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /api/v1/Events/{id}
     * @param id 
     * @param updateEventRequest 
     */
    updateEvent(id: string, updateEventRequest: UpdateEventRequest, extraHttpRequestParams?: any): Observable<{}>;

}
