/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateLocationRequest } from '../model/models';
import { LocationDto } from '../model/models';
import { LocationEventDto } from '../model/models';
import { PagedResultOfLocationDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateLocationRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LocationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/Locations
     * @param createLocationRequest 
     */
    createLocation(createLocationRequest: CreateLocationRequest, extraHttpRequestParams?: any): Observable<LocationDto>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/Locations/{id}
     * @param id 
     */
    deleteLocation(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Locations/{id}/events
     * @param id 
     */
    getEventsByLocation(id: string, extraHttpRequestParams?: any): Observable<Array<LocationEventDto>>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Locations/{id}
     * @param id 
     */
    getLocationById(id: string, extraHttpRequestParams?: any): Observable<LocationDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Locations
     * @param name 
     * @param city 
     * @param page 
     * @param pageSize 
     */
    getLocations(name?: string, city?: string, page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<PagedResultOfLocationDto>;

    /**
     * 
     * 
     * @endpoint put /api/v1/Locations/{id}
     * @param id 
     * @param updateLocationRequest 
     */
    updateLocation(id: string, updateLocationRequest: UpdateLocationRequest, extraHttpRequestParams?: any): Observable<{}>;

}
