/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateOrderRequest } from '../model/models';
import { OrderDto } from '../model/models';
import { PagedResultOfOrderSummaryDto } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OrdersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/Orders/{id}/cancel
     * @param id 
     */
    cancelOrder(id: string, extraHttpRequestParams?: any): Observable<OrderDto>;

    /**
     * 
     * 
     * @endpoint post /api/v1/Orders
     * @param createOrderRequest 
     */
    createOrder(createOrderRequest: CreateOrderRequest, extraHttpRequestParams?: any): Observable<OrderDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Orders/mine
     * @param page 
     * @param pageSize 
     */
    getMyOrders(page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<PagedResultOfOrderSummaryDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Orders/{id}
     * @param id 
     */
    getOrderById(id: string, extraHttpRequestParams?: any): Observable<OrderDto>;

    /**
     * 
     * 
     * @endpoint post /api/v1/Orders/{id}/pay
     * @param id 
     */
    payOrder(id: string, extraHttpRequestParams?: any): Observable<OrderDto>;

}
