/**
 * Ticket Booking Platform API - v1
 *
 * Contact: m1musbal@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PagedResultOfTicketDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { TicketDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TicketsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/v1/Tickets/mine
     * @param status 
     * @param page 
     * @param pageSize 
     */
    getMyTickets(status?: string, page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<PagedResultOfTicketDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/Tickets/{id}
     * @param id 
     */
    getTicketById(id: string, extraHttpRequestParams?: any): Observable<TicketDto>;

}
